### ISSUE TITLE
Code Name Drowned, Online Not Work at all- Steam Deck

### ISSUE THREAD

**Issue by R-Dust** [minecraft-linux/mcpelauncher-manifest#770]
**Describe the bug**
Everytime you load up any version on the steam deck, you will always get code name Drowned, cant not be fixed by my efforts

**To Reproduce**
Load up Minecraft bedrock launcher on steam deck, Try to log into online, you will get the error drowned, no matter the version

**Expected behavior**
exactly that^

**Screenshots**
![image](https://user-images.githubusercontent.com/123765725/215161943-74f6894d-c035-44a4-893a-1326ecc2e109.png)

**Desktop (please complete the following information):**
 - OS: Steam OS/Linux
 - Version : Minecraft_Bedrock_Launcher-x86_64-v0.8.0.700.AppImage
 - Installation Type: App Image

**Additional context**

**Comment by NotLukario** [comment]
I'm struggling with this too

**Comment by LennyMcLennington** [comment]
I have the same issue, happens on AppImage, Flatpak, and from AUR... On my desktop PC it works fine with Arch Linux but on SteamOS it just has the error code Drowned.

**Comment by LennyMcLennington** [comment]
I updated to preview channel of SteamOS, and also I changed my default browser in the Plasma Settings.

I have no idea whether either of these things actually fixed it, but something did, and now I can sign in.

My best guess is that either something was fixed in the SteamOS update, or that changing my default browser in the "Default Applications" section of the Plasma Settings forced the config used by xdg-open to update and maybe it was previously broken or something (I was having other issues related to opening links / files in other apps beforehand and this also fixed those). I have no clue though, maybe it was something else entirely. Just letting people know on the off chance this helps someone.

**Comment by milkydelta** [comment]
I'm running the AppImage on SteamOS stable. I was asked to update the launcher when I opened it. The game now connects to my microsoft account effortlessly.

**Comment by Boblet67** [comment]
I got this and I,m not on the steam deck. 

Although it has a window that says:

> 
> Failed to open Xboxlive login Window. Please look into the gamelog for more Information: Process exited with status=255 stdout:`` stderr:`Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway. QQmlApplicationEngine failed to load component qrc:/main.qml:3:1: module "QtWebEngine" is not installed `

I also get this in the terminal:
> Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.


I don't think i have the same issue but it might be similar and it is still an issue.

**Comment by Pokepunch** [comment]
I'm getting this on Steam Deck. 
OS: SteamOS 3.5.1
Version: Minecraft_Bedrock_Launcher-x86_64-v0.11.4.721.AppImage
Installation Type: App Image

**Comment by weeowey** [comment]
Also having this drowned issue. Also on Steam Deck tried to get some information out of the debug mode in the terminal, only thing i see  on mine to do with connections is "Implicitly defined onFoo properties in Connections are deprecated"
OS: SteamOS 3.5.7
Version: v0.12.00 (builld 72)
installation type: SteamOS Discover  (Flatpak)
