### ISSUE TITLE
Sprinting & Strafing not working in the newer versions.

### ISSUE THREAD

**Issue by Avo4D** [minecraft-linux/mcpelauncher-manifest#870]
**Describe the bug**
Above 1.19.50/40, I cant strafe & sprint which may seem useless but when referring to PVP Servers like Zeqa. This is a very unfair bug and gives an advantage to the opponents. I can fix it by downgrading to 1.19.40 but many servers wont let me play on this version because its outdated.

**To Reproduce**
1. Open Minecraft Bedrock Launcher
2. Choose 1.19.83.01
3. Join a server/world
4. No Sprint & Strafe mechanics.

**Expected behavior**
I should be able to strafe & sprint like on the UWP Version so that the opponent cant aim properly.

**Desktop (please complete the following information):**
 - OS: Linux
 - Version Flatpak v0.10.0
 - Installation Type Flathub

**Additional context**
I would really like this to be fixed because I play Minecraft just for PvP because I find it fun but this bug makes others look like they are hacking.

**Comment by aguywithagithubaccount** [comment]
same here. i have kubuntu 23.10 with the appimage version

**Comment by Mqkji** [comment]
Yup. This is a huge problem for me, and you cannot join servers on 1.19- anymore, it gives you an error, depending on what server you're trying to join. I'd like for this to be fixed

**Comment by ChristopherHX** [comment]
If you would like this to be fixed, please tell mojang that they need to fix this bug.

- We don't have the source code of the game
- We don't have debugging information of the game
  - Recently mojang removed another bunch of them from the binary and forced us to use the android interface for keyboard and mouse input with less mappable keys
  

Include the affected device coming with android x86_64 preinstalled, reports of Android VM's / this launcher don't get real attention as mojang don't provide support for them. The last x86_64 intel bugs (crafting + textures off by one) has been solved by accident and mojang never confirmed that they have actively fixed it, that took about 1 year.

If you don't care about money, there are rumors that you can
- buy the chomeos version of Minecraft on a special chomeos version you can install maybe also in a VM
- extract the apk from that ChromeOS
- Use the import apk function to install Minecraft ChromeOS Version into the launcher
- launch the Minecraft ChromeOS Version
- Notice that your bug is gone while using a much newer game version

**Disclaimer** I never bought the expensive ChromeOS Version, because I never ever used that feature of the game until I saw bug reports about a bug that happens also on Bluestacks x86_64 via intel processor.

Another rumor is that amd processors are not affected. (I don't have such a cpu) 

Confirmed is that arm64 processesors are neither affected on Android or via this launcher.
=> m1/m2/m3 macbooks don't suffer with the cheap Android Game and just can strafe sprint
=> nintendo switch also can stafe sprint using this launcher

**Comment by Mqkji** [comment]
its seems to have been fixed on the android version for quite a while now tho

**Comment by lightyisreal** [comment]
> its seems to have been fixed on the android version for quite a while now tho

x86_64 or ARM64?

**Comment by Mqkji** [comment]
no idea

**Comment by OpenSauce04** [comment]
This is definitely not fixed on x86, as I can replicate it on the latest beta

**Comment by Nicktufrum** [comment]
is there any latest version without the issue like i 1.21 or 1.20 it is really really and really big problem especially for pvp or anyone who has chromebook apk please tell

**Comment by lightyisreal** [comment]
That would be piracy, though

-------- Original Message --------

**Comment by Nicktufrum** [comment]
sometimes piracy is necessary

**Comment by lightyisreal** [comment]
All I can say then is good luck. I'm not gonna help you with that.

**Comment by avoladrian1** [comment]
Hey guys, New account here.

> Another rumor is that amd processors are not affected. (I don't have such a cpu)

On my newer hardware, with an AMD processor, the issue seems to be resolved for me.
I can try to post video proof if you want me to.

But this point may also be false and it only works on specified CPUs, i don't know.

> x86_64 or ARM64?

Most likely x86_64. On my mobile device, strafe & sprint mechanics work perfectly fine...

> is there any latest version without the issue like i 1.21 or 1.20

I am sure this isn't fixed in the newer versions.
You can check changelogs' of recent Bedrock versions.
There should be stuff saying that "`bug-id` is fixed" or something similiar.

**Comment by AlphaCraft9658** [comment]
This issue still appears for me.
